spring.application.name=back

spring.datasource.url=jdbc:postgresql://localhost:5432/gestion
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
<<<<<<< HEAD
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
=======

# Configuración de Email - Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=karenjuliethzabaleta999@gmail.com
spring.mail.password=odge jyay dsjy qiiy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
>>>>>>> c58474b2d4e77f8e63c05950c2f64bca7b9a88d2
