ALTER TABLE admin.rrhh ADD COLUMN IF NOT EXISTS documento VARCHAR(20);
ALTER TABLE admin.rrhh ADD COLUMN IF NOT EXISTS cargo VARCHAR(100);
ALTER TABLE admin.rrhh ADD COLUMN IF NOT EXISTS ultimo_acceso TIMESTAMP;
